### ISSUE TITLE
Дз5

### ISSUE THREAD

**Issue by Sofya112** [MIEE-ACS/domashnee-zadanie-no5-Sofya112#1]
Проверка прошла успешно, надеюсь, что и Ваша проверка пройдет успешно :)

**Comment by d-makarenko** [comment]
Несколько замечаний:
Созданный класс Counter по сути не используется. В самом начале создается несколько экземпляров и на этом все. 
Я повторяюсь, конечно, но все же: идея ооп заключается в том, что мы объединяем в классе данные и методы для их обработки. В этом задании у нас есть данные - текущее значение счетчика и методы: увеличить и уменьшить. В твоем решении все размазано по коду класса MainWindow.
И в итоге пришлось прибегать к "хаку" со скрытым текстовым полем.

Я выложил в репозиторий свои правки, просмотри пожалуйста.
